setup build-user-img, conda-build & test-user-package for dev-testing :mag:

diff --git a/.github/workflows/build-user-image.yml b/.github/workflows/build-user-image.yml
--- a/.github/workflows/build-user-image.yml
+++ b/.github/workflows/build-user-image.yml
@@ -1,17 +1,22 @@
 name: Build User Image
 
 on:
-  workflow_run:
-    workflows: ["Test User Package"]
-    types:
-      - completed
+  workflow_call:
+    inputs:
+      verstag:
+        type: string
+        required: true
+      latest:
+        type: boolean
+        required: false
+        default: false
 
   workflow_dispatch:
     inputs:
       gitrev:
         type: string
         required: true
-        description: "gitrev: commit (full), tag or branch (branch is not unique and therefore step could get cached)"
+        description: "gitrev: commit-hash (full), tag or branch (branch is not unique and therefore checkout-step could get cached)"
       verstag:
         type: string
         required: true
@@ -31,13 +36,8 @@ env:
   REGISTRY: ghcr.io
 
 jobs:
-  build-and-push-image:
+  build-test-and-push-image:
     runs-on: ubuntu-latest
-    if: ${{ (github.event.workflow_run.conclusion == 'success') || (github.event_name == 'workflow_dispatch') }}
-    permissions:
-      contents: read
-      packages: write
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -63,24 +63,26 @@ jobs:
       - name: Setup metadata img-name & img-tag
         shell: bash -l {0}
         run: |
-          if [[ ${{ github.event_name }} == "workflow_run" ]]
-          then
-            echo "latest=true" >> "$GITHUB_ENV"
-            echo "version=${{ steps.get-latest-tag.outputs.tag }}" >> "$GITHUB_ENV"
-            echo "gitrev=${{ steps.get-latest-tag.outputs.tag }}" >> "$GITHUB_ENV"
+          if [[ ${{ github.event_name }} == "workflow_call" ]]; then
+            echo "gitrev=${{ inputs.verstag }}" >> "$GITHUB_ENV"
             echo "build=user" >> "$GITHUB_ENV"
-          fi
-          if [[ ${{ github.event_name }} == "workflow_dispatch" ]]
-          then
-            echo "latest=${{ inputs.latest }}" >> "$GITHUB_ENV"
-            echo "version=${{ inputs.verstag }}" >> "$GITHUB_ENV"
+          elif [[ ${{ github.event_name }} == "workflow_dispatch" ]]; then
             echo "gitrev=${{ inputs.gitrev }}" >> "$GITHUB_ENV"
-            if [[ ${{ inputs.test }} == "true" ]]
-            then
+            if [[ ${{ inputs.test }} == "true" ]]; then
               echo "build=test" >> "$GITHUB_ENV"
             else
               echo "build=user" >> "$GITHUB_ENV"
             fi
+          else
+            echo "Invalid github-event!"
+            exit 2
+          fi
+          echo "latest=${{ inputs.latest }}" >> "$GITHUB_ENV"
+          echo "version=${{ inputs.verstag }}" >> "$GITHUB_ENV"
+          DEV_STR="dev"
+          if [[ "${{ inputs.verstag }}" == *"$DEV_STR"* ]] && [[ $LATEST_DOCKER == 'true' ]]; then
+            echo "Invalid configuration of workflow-inputs!"
+            exit 2
           fi
       - name: Extract metadata (tags, labels) for Docker
         id: meta
diff --git a/.github/workflows/test-user-package.yml b/.github/workflows/test-user-package.yml
--- a/.github/workflows/test-user-package.yml
+++ b/.github/workflows/test-user-package.yml
@@ -1,13 +1,38 @@
 name: Test User Package
 
 on:
-  workflow_run:
-    workflows: ["Conda Build"]
-    types:
-      - completed
+  workflow_dispatch:
+    inputs:
+      version:
+        type: string
+        required: true
+        description: "version: PEP440 package-version (incl. leading 'v')"
+      buildDocker:
+        type: boolean
+        required: false
+        default: false
+        description: "build docker-img if tests succeeded?"
+      latestDocker:
+        type: boolean
+        required: false
+        default: false
+        description: "tag docker-img as latest (if `buildDocker` is enabled)"
+  workflow_call:
+    inputs:
+      version:
+        type: string
+        required: true
+      buildDocker:
+        type: boolean
+        required: false
+        default: false
+      latestDocker:
+        type: boolean
+        required: false
+        default: false
 
 jobs:
-  conda-build:
+  test-conda-build:
     runs-on: ubuntu-latest
     if: ${{ github.event.workflow_run.conclusion == 'success' }}
     steps:
@@ -18,13 +43,20 @@ jobs:
       - name: Set variables, Install Package & Dependencies
         shell: bash -l {0}
         run: |
+          KARABO_TAG=${{ inputs.version }}
+          KARABO_VERSION="${KARABO_TAG:1}"
+          DEV_STR="dev"
+          if [[ "$KARABO_VERSION" == *"$DEV_STR"* ]] && [[ "${{ inputs.latestDocker }}" == 'true' ]]; then
+            echo "Invalid configuration of workflow-inputs!"
+            exit 2
+          fi
           export IS_GITHUB_RUNNER=true
           export RUN_NOTEBOOK_TESTS=false
           conda install -y -n base conda-libmamba-solver
           conda config --set solver libmamba
           conda create -y -n karabo-env python=3.9
           conda activate karabo-env
-          conda install -y -c nvidia/label/cuda-11.7.0 -c i4ds -c conda-forge karabo-pipeline=${{ env.KARABO_VERSION }}
+          conda install -y -c nvidia/label/cuda-11.7.0 -c i4ds -c conda-forge karabo-pipeline=$KARABO_VERSION
           pip install ipykernel
           python -m ipykernel install --user --name python3
       - name: Test Package
@@ -32,4 +64,14 @@ jobs:
         run: |
           conda activate karabo-env
           pytest --pyargs karabo.test
+
+  build-docker:
+    needs: test-conda-build
+    if: ${{ inputs.buildDocker == 'true' }}
+    uses: ./.github/workflows/build-user-image.yml
+    with:
+      verstag: ${{ inputs.version }}
+      latest: ${{ inputs.latestDocker }}
+
+
   
